# Run pytest
#

name: Run tests

on:
  push:
    branches-ignore: 
      - main
  pull_request:
    branches-ignore: 
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements/dev.txt
    - name: Test with pytest
      run: |
        python -m pytest
